version: '3.9'

services:
  postgres:
    container_name: nest-notify-db
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    networks:
      - nest-notify

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-notify-app
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    networks:
      - nest-notify
volumes:
  postgres-data:

networks:
  nest-notify: